# Generated by Django 4.0.6 on 2022-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True, verbose_name='태그슬러그'),
        ),
    ]
