# Generated by Django 4.0.6 on 2022-07-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
